version: "1.0"
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db


  db:
    platform: linux/x86_64
    image: mysql:5.7.34
    restart: always
    environment:
      MYSQL_DATABASE: gomin
      MYSQL_USER: exy
      MYSQL_PASSWORD: exypassword
      MYSQL_ROOT_PASSWOR: exypassword
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33011:3306